### ISSUE TITLE
got an error in objective c

### ISSUE THREAD

**Issue by jorden0154** [AuthorizeNet/accept-sdk-ios#27]
[handler getTokenWithRequest:request successHandler:^(AcceptSDKTokenResponse * _Nonnull token) {
        NSLog(@"success %@", token.getOpaqueData.getDataValue);
    } failureHandler:^(AcceptSDKErrorResponse * _Nonnull error) {
        NSLog(@"failed... );
    }];

I got error here "EXC_BAD_ACCESS"

**Comment by davidolesch** [comment]
@RakeshVisa can you provide an example Objective-C implementation? 

https://gist.github.com/davidolesch/266a4553897386a800e7e5e00113cf8b

My implementation crashes on line 25 with a EXC_BAD_ACCESS exception. I think it might be an issue with the bridging because I don't have any problems using the SDK in Swift. Unfortunately I need to use it in a Objective-C.

**Comment by sprewell20051116** [comment]
Hi @davidolesch  did you solve this problem? 
I also got EXC_BAD_ACCESS exception with Objective-C implementation.

**Comment by davidolesch** [comment]
No. Instead I just implemented the validation and API requests the SDK does in Objective-C. The Swift code is open source so you can see how they do it.

**Comment by sprewell20051116** [comment]
@davidolesch 
Thanks for your suggestion.

**Comment by sprewell20051116** [comment]
@davidolesch May I know which swift code did you reference?

**Comment by davidolesch** [comment]
@sprewell20051116 https://github.com/AuthorizeNet/accept-sdk-ios/tree/master/AcceptSDK

**Comment by sprewell20051116** [comment]
@davidolesch thank you !!!

**Comment by ptaneja** [comment]
Will include the Objective-C demo app. Closing the issue for now.
