### ISSUE TITLE
Import AcceptSDK in swift project shows error

### ISSUE THREAD

**Issue by sprewell20051116** [AuthorizeNet/accept-sdk-ios#28]
After pod install and import "AcceptSDK" shows
'Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2'
Xcode : Version 8.2.1 (8C1002)

**Comment by adavidw** [comment]
Hi,

This module hasn't (yet) been compiled against the latest Swift libraries, so that's why you get the error if you're installing it in a more recent version of Xcode.

A workaround is to download and install the Swift 3.0.0 toolchain from https://swift.org/download. Then you can select that version of Swift to use in Xcode.

**Comment by CHINAZB** [comment]
Hi,man

What can I do that importing "AcceptSDK" into my project with Swift2.3 ？ Do you have any other 
version of SDK?

Look forward to your reply，thanks very much !

**Comment by sprewell20051116** [comment]
@adavidw Thank you very much! The workaround works for me.

**Comment by bt1** [comment]
@sprewell20051116 were you able to solve this?

**Comment by hatboyzero** [comment]
Seeing this same issue with the latest release of XCode:

`Error:(7, 8) module compiled with Swift 4.0 cannot be imported in Swift 4.0.2`

I'm assuming this is because the pod has not been built against the latest.  Reverting to the 4.0 toolchain for now.

**Comment by RakeshVisa** [comment]
We have updated our SDK. Please update the pod and try again (make sure you run pod repo update first). If you still face the problem please get back to us.
