### ISSUE TITLE
Please update to Swift 3.1

### ISSUE THREAD

**Issue by hjuraev** [AuthorizeNet/accept-sdk-ios#33]

**Comment by datureezy** [comment]
you might want to implement rest api calls in your app instead. they haven't updated the project since the beginning of this year. they will update to 3.1, lock it at that version, and when wwdc hits and swift upgrades to even  0.0.1 higher, their sdk will be useless once again for 4-6 months. 

be mindful when you do use the rest api though. their api does not accept json properly, it requires your json object to be in the order they detail in their api documentation, which is a huge headache to work around. i had to post xml to their backend instead. it works, but it's not as fast as desired.

**Comment by datureezy** [comment]
at this time, yes, the keys are stored on the app which should not be done according to documentation. when the app moves into production, the plan is to fetch the keys from a server; keys being released only to authenticated users.

**Comment by sam2000** [comment]
@datureezy Thanks for the response. I manage to recompile the Source to Swift 3.1 without any issues so I am using the SDK for now.Thanks very much

**Comment by sagarmilani** [comment]
@sam2000 can you provide steps for same?

**Comment by sam2000** [comment]
@sagarmilani
It is a while since I did that but i didn't do anything special
 I just got the source files, opened them in the latest version of 8.x which uses Swift 3.1 by default. Then I ran a build and used it. Does this make sense?

**Comment by Mindbowser** [comment]
@sam2000 you dragged the source files inside xcode project or what?

**Comment by ptaneja** [comment]
Updated to 4.0. Please check
